apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJRMkZ5WVcxbGFXdzZaMmh3WDBrNVkyNXFNMlIyY0ZsaGRFZGlNbmhOVEdFeWVEaE5jVVpxYVhNeGJURXdkRkUxWnc9PSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcC5leGUiCn0K
type: kubernetes.io/dockerconfigjson
